---
title: "Exercises_1"
author: "Hans Franke"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=TRUE}

library(tidyverse)
library(ISLR)

```

# General Graph Grammar


ggplot(data = <DATA>) +   
  <GEOM_FUNCTION>(  
     mapping = aes( < MAPPINGS > ),  
     stat = < STAT > ,   
     position = < POSITION >  
  ) +  
  < COORDINATE_FUNCTION > +  
  < FACET_FUNCTION >  

# Question 1:
## Name the aesthetics, geoms, scales, and facets of the above visualisation. Also name any statistical transformations or special coordinate systems.

```{r}
head(Hitters)
```

```{r, }
# histogram of the distribution of salary
hist(Hitters$Salary, xlab = "Salary in thousands of dollars")
```


1. Aesthetic
2. Geoms
3. Scales
4. Facets

```{r}
# barplot of how many members in each league
barplot(table(Hitters$League))
```

1. Aesthetic
2. Geoms
3. Scales
4. Facets

```{r}
homeruns_plot <- 
  ggplot(Hitters, aes(x = Hits, y = HmRun)) +
  geom_point() +
  labs(x = "Hits", y = "Home runs")

homeruns_plot
```


```{r}
homeruns_plot + 
  geom_density_2d() +
  labs(title = "Cool density and scatter plot of baseball data") +
  theme_minimal()
```


